name: Ejecutar Notebook Diariamente

on:
  schedule:
    - cron: '30 14 * * *'  # 14:30 UTC = 16:30 CEST
  workflow_dispatch: {}

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"   # imprime sin buffer (mejor para ver print en logs)
      # Carga tus credenciales desde Secrets (no las hardcodees en el notebook)
      MOODLE_USER: ${{ secrets.MOODLE_USER }}
      MOODLE_PASS: ${{ secrets.MOODLE_PASS }}
      GMAIL_APP_PASS: ${{ secrets.GMAIL_APP_PASS }}

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Google Chrome (estable)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-linux.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-linux.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Instalar dependencias Python
        run: |
          python -m pip install --upgrade pip
          pip install papermill ipykernel nbconvert
          pip install selenium webdriver-manager
          pip install yagmail keyring keyrings.alt css_inline beautifulsoup4 premailer

      # Si tu .ipynb está en la raíz del repo:
      - name: Ejecutar Notebook con Papermill (ver prints en logs)
        run: |
          papermill LaSalle2.ipynb LaSalle2_ejecutado.ipynb --log-output --progress-bar False

      - name: Exportar salida a HTML (opcional)
        run: |
          jupyter nbconvert --to html LaSalle2_ejecutado.ipynb

      - name: Subir artefactos
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: |
            LaSalle2_ejecutado.ipynb
            LaSalle2_ejecutado.html
